### PR TITLE
Development To Main (First Prototype)

### PR DESCRIPTION
**Pull request by SageSG**
Woohoo!

### CODE REVIEW

**Review by Don-Whis — APPROVED** [review]

**Comment by nbinged** [comment]
Good

**Review by nbinged — APPROVED** [review]
Testing working. good

**Review by nbinged — CHANGES_REQUESTED** [review]
For Windows users:
Add/edit in these 2 lines:

import pytesseract

if(os.name == 'nt'):
    pytesseract.pytesseract.tesseract_cmd = "C:/Program Files/Tesseract-OCR/tesseract.exe"  # Path of where pytesseract.exe is located

# Requires the Tesseract OCR files inside the working directory
# if(os.name == 'nt'):
#    pytesseract.pytesseract.tesseract_cmd = "Tesseract-OCR/tesseract.exe"

**Review by pureskill714 — APPROVED** [review]
Able to compile and run as expected!

**Review by yaoyujing — APPROVED** [review]
approved, good jobbbbbbbb

**Pull request merged**
